version: '3'

volumes:
  pg_data:
  static:
  media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: dockeruser1799/foodgram_backend
    env_file: .env
    volumes:
    - media:/app/media
    - static:/app/backend_static
    depends_on:
    - db
  
  frontend:
    env_file: .env
    image: dockeruser1799/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: dockeruser1799/foodgram_gateway
    env_file: .env
    volumes:
      - media:/media
      - static:/static/
    ports:
      - 8080:80
    depends_on:
    - backend
