# Константы моделей recipes
NAME_MAX_LENGTH = 128
MEASUREMENT_UNIT_MAX_LENGTH = 64
TAG_FIELDS_MAX_LENGTH = 32
SHORT_LINK_LENGTH = 10
MIN_COOKING_TIME = 1
INGREDIENT_MIN_LIMIT = 1

# Константы моделей users
USER_FIELDS_MAX_LENGTH_150 = 150
