# Generated by Django 3.2.16 on 2024-05-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20240517_1747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredientsmodel',
            options={'default_related_name': 'recipeingredients', 'verbose_name': 'Ингридиент в рецепте', 'verbose_name_plural': 'Ингридиенты в рецепте'},
        ),
        migrations.RemoveField(
            model_name='recipeingredientsmodel',
            name='measurement_unit',
        ),
        migrations.AlterField(
            model_name='recipeingredientsmodel',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredients', to='recipes.ingredientmodel'),
        ),
        migrations.AlterField(
            model_name='recipeingredientsmodel',
            name='recipe_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipeingredients', to='recipes.recipemodel'),
        ),
    ]
