# Generated by Django 3.2.16 on 2024-05-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20240525_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipemodel',
            options={'default_related_name': 'recipes', 'ordering': ('-created_at',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
