# Generated by Django 3.2.16 on 2024-05-29 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_recipemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientmodel',
            options={'default_related_name': 'ingredient', 'ordering': ('name',), 'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterField(
            model_name='ingredientmodel',
            name='measurement_unit',
            field=models.CharField(max_length=16, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='recipeingredientsmodel',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Нужно назначить количество ингредиентов.')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Нужно назначить время приготовления.')], verbose_name='Время приготовления, мин.'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritemodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartmodel',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='favoritemodel',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_recipe_user_favor'),
        ),
        migrations.AddConstraint(
            model_name='ingredientmodel',
            constraint=models.UniqueConstraint(fields=('name', 'measurement_unit'), name='unique_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='recipeingredientsmodel',
            constraint=models.UniqueConstraint(fields=('recipe_name', 'name'), name='unique_ingredient_in_recipe'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartmodel',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_recipe_user_cart'),
        ),
    ]
