# Generated by Django 3.2.16 on 2024-05-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'ordering': ('username',)},
        ),
        migrations.AddField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='images/avatars/'),
        ),
        migrations.AddField(
            model_name='foodgramuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=150),
        ),
    ]
