# Generated by Django 3.2.16 on 2024-05-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240519_1048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientmodel',
            options={'default_related_name': 'ingredient', 'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
    ]
