# Generated by Django 3.2.16 on 2024-05-21 11:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20240521_1238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritemodel',
            unique_together={('user', 'recipe')},
        ),
    ]
