# Generated by Django 3.2.16 on 2024-05-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20240529_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodel',
            name='short_link',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Короткая ссылка'),
        ),
    ]
