# Generated by Django 3.2.16 on 2024-05-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_foodgramuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodgramuser',
            name='role',
        ),
    ]
